//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.27 at 08:28:01 PM UZT 
//


package com.example.taskwebservice.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CancelTransactionResult", propOrder = {
    "transactionState"
})
public class CancelTransactionResult
    extends GenericResult
{

    protected int transactionState;

    /**
     * Gets the value of the transactionState property.
     * 
     */
    public int getTransactionState() {
        return transactionState;
    }

    /**
     * Sets the value of the transactionState property.
     * 
     */
    public void setTransactionState(int value) {
        this.transactionState = value;
    }

}
