//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.27 at 08:28:01 PM UZT 
//


package com.example.taskwebservice.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CheckTransactionResult", propOrder = {
    "providerTrnId",
    "transactionState",
    "transactionStateErrorStatus",
    "transactionStateErrorMsg"
})
public class CheckTransactionResult
    extends GenericResult
{

    protected long providerTrnId;
    protected int transactionState;
    protected int transactionStateErrorStatus;
    @XmlElement(required = true)
    protected String transactionStateErrorMsg;

    /**
     * Gets the value of the providerTrnId property.
     * 
     */
    public long getProviderTrnId() {
        return providerTrnId;
    }

    /**
     * Sets the value of the providerTrnId property.
     * 
     */
    public void setProviderTrnId(long value) {
        this.providerTrnId = value;
    }

    /**
     * Gets the value of the transactionState property.
     * 
     */
    public int getTransactionState() {
        return transactionState;
    }

    /**
     * Sets the value of the transactionState property.
     * 
     */
    public void setTransactionState(int value) {
        this.transactionState = value;
    }

    /**
     * Gets the value of the transactionStateErrorStatus property.
     * 
     */
    public int getTransactionStateErrorStatus() {
        return transactionStateErrorStatus;
    }

    /**
     * Sets the value of the transactionStateErrorStatus property.
     * 
     */
    public void setTransactionStateErrorStatus(int value) {
        this.transactionStateErrorStatus = value;
    }

    /**
     * Gets the value of the transactionStateErrorMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionStateErrorMsg() {
        return transactionStateErrorMsg;
    }

    /**
     * Sets the value of the transactionStateErrorMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionStateErrorMsg(String value) {
        this.transactionStateErrorMsg = value;
    }

}
