//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.27 at 08:28:01 PM UZT 
//


package com.example.taskwebservice.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GenericParam", propOrder = {
    "paramKey",
    "paramValue"
})
public class GenericParam {

    @XmlElement(required = true)
    protected String paramKey;
    @XmlElement(required = true)
    protected String paramValue;

    /**
     * Gets the value of the paramKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParamKey() {
        return paramKey;
    }

    /**
     * Sets the value of the paramKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParamKey(String value) {
        this.paramKey = value;
    }

    /**
     * Gets the value of the paramValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParamValue() {
        return paramValue;
    }

    /**
     * Sets the value of the paramValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParamValue(String value) {
        this.paramValue = value;
    }

}
