//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.27 at 08:28:01 PM UZT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://uws.provider.com/")
package com.example.taskwebservice.dto;
